package com.example.template

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import com.example.pigeon_features.feature.ConfigurePigeonApi
import com.example.pigeon_features.feature.MessageFromNative
import com.example.pigeon_features.feature.PigeonBridge
import com.example.pigeon_features.feature.FromFlutter

class MainActivity : FlutterActivity() {


    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        val messenger = flutterEngine.dartExecutor.binaryMessenger
        PigeonBridge.initialize(messenger)

        ConfigurePigeonApi.setUp(
            messenger,
            MyConfigurePigeonApiImpl()
        )

        MessageFromNative.setUp(
            messenger,
            MyMessageFromNativeImpl()
        )
    }
}


// 3. You must implement the interfaces generated by Pigeon
class MyConfigurePigeonApiImpl : ConfigurePigeonApi {
    override fun ping() {
        println("Ping received from Flutter!")
        PigeonBridge.sendConnectionStatus(true)
    }
}

class MyMessageFromNativeImpl : MessageFromNative {
    override fun greetUser(username: String) {
        println("Greeting user: $username")
        PigeonBridge.sendConnectionStatus(true)
    }
}
